% plot skeleton 
% edit by Huahui Chen 2017.3.11
close all
filename = '/home/chh/icme/nturgb+d_skeletons/S003C003P019R002A054.skeleton';
bodyinfor = read_skeleton_file(filename);
figure
for frame = 1 : length(bodyinfor)
    % plot every frame
    
    for body = 1 : length(bodyinfor(frame).bodies)
        for joint = 1 : 25
            plot3(bodyinfor(frame).bodies(body).joints(joint).x, ...
                bodyinfor(frame).bodies(body).joints(joint).y, ...
                bodyinfor(frame).bodies(body).joints(joint).z, '*');
            
            
            text(bodyinfor(frame).bodies(body).joints(joint).x, ...
                bodyinfor(frame).bodies(body).joints(joint).y, ...
                bodyinfor(frame).bodies(body).joints(joint).z, num2str(joint));
            
            
            hold on

        end
        line_seq = [20, 19, 18, 17, 1, 2, 21, 9, 10, 11, 12, 25];
        for i = 1 : length(line_seq) - 1
            line([bodyinfor(frame).bodies(body).joints(line_seq(i)).x, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).x], ...
                 [bodyinfor(frame).bodies(body).joints(line_seq(i)).y, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).y], ...
                 [bodyinfor(frame).bodies(body).joints(line_seq(i)).z, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).z])
        end
        line_seq = [12 25];
        for i = 1 : length(line_seq) - 1
            line([bodyinfor(frame).bodies(body).joints(line_seq(i)).x, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).x], ...
                 [bodyinfor(frame).bodies(body).joints(line_seq(i)).y, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).y], ...
                 [bodyinfor(frame).bodies(body).joints(line_seq(i)).z, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).z])
        end
        line_seq = [21 3 4];
        for i = 1 : length(line_seq) - 1
            line([bodyinfor(frame).bodies(body).joints(line_seq(i)).x, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).x], ...
                 [bodyinfor(frame).bodies(body).joints(line_seq(i)).y, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).y], ...
                 [bodyinfor(frame).bodies(body).joints(line_seq(i)).z, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).z])
        end
        line_seq = [16, 15, 14, 13, 1, 2, 21, 5, 6, 7, 8, 22];
        for i = 1 : length(line_seq) - 1
            line([bodyinfor(frame).bodies(body).joints(line_seq(i)).x, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).x], ...
                 [bodyinfor(frame).bodies(body).joints(line_seq(i)).y, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).y], ...
                 [bodyinfor(frame).bodies(body).joints(line_seq(i)).z, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).z])
        end
        line_seq = [8 23];
        for i = 1 : length(line_seq) - 1
            line([bodyinfor(frame).bodies(body).joints(line_seq(i)).x, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).x], ...
                 [bodyinfor(frame).bodies(body).joints(line_seq(i)).y, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).y], ...
                 [bodyinfor(frame).bodies(body).joints(line_seq(i)).z, ...
                bodyinfor(frame).bodies(body).joints(line_seq(i + 1)).z])
        end
    end
    view(0, 90) %xy plane view(az, el)
%     view(90, 0) % yz
    axis([-0.7, 1, -2, 1, 0, 4])
    xlabel('x')
    ylabel('y')
    zlabel('z')
    hold off % clear last plot
    pause(0.1)
end

